/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthSyncRouteImport } from './routes/auth/sync'
import { Route as AuthExtensionSyncRouteImport } from './routes/auth/extension-sync'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminWaitlistRouteImport } from './routes/admin/waitlist'
import { Route as AdminLegalRouteImport } from './routes/admin/legal'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSyncRoute = AuthSyncRouteImport.update({
  id: '/auth/sync',
  path: '/auth/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthExtensionSyncRoute = AuthExtensionSyncRouteImport.update({
  id: '/auth/extension-sync',
  path: '/auth/extension-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/trash': typeof TrashRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/extension-sync': typeof AuthExtensionSyncRoute
  '/auth/sync': typeof AuthSyncRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/trash': typeof TrashRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/extension-sync': typeof AuthExtensionSyncRoute
  '/auth/sync': typeof AuthSyncRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/trash': typeof TrashRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/extension-sync': typeof AuthExtensionSyncRoute
  '/auth/sync': typeof AuthSyncRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/search'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/trash'
    | '/admin/legal'
    | '/admin/waitlist'
    | '/auth/callback'
    | '/auth/extension-sync'
    | '/auth/sync'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/search'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/trash'
    | '/admin/legal'
    | '/admin/waitlist'
    | '/auth/callback'
    | '/auth/extension-sync'
    | '/auth/sync'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/search'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/trash'
    | '/admin/legal'
    | '/admin/waitlist'
    | '/auth/callback'
    | '/auth/extension-sync'
    | '/auth/sync'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TrashRoute: typeof TrashRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthExtensionSyncRoute: typeof AuthExtensionSyncRoute
  AuthSyncRoute: typeof AuthSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/sync': {
      id: '/auth/sync'
      path: '/auth/sync'
      fullPath: '/auth/sync'
      preLoaderRoute: typeof AuthSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/extension-sync': {
      id: '/auth/extension-sync'
      path: '/auth/extension-sync'
      fullPath: '/auth/extension-sync'
      preLoaderRoute: typeof AuthExtensionSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLegalRoute: typeof AdminLegalRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLegalRoute: AdminLegalRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TrashRoute: TrashRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthExtensionSyncRoute: AuthExtensionSyncRoute,
  AuthSyncRoute: AuthSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
