import type { Note } from "./note";
import type { Profile } from "./user";

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        // Profile creation is handled by Supabase Auth triggers usually,
        // but if manual creation is needed:
        Insert: Profile;
        // id, email are immutable identity fields
        Update: Partial<Omit<Profile, "id" | "email">>;
      };
      notes: {
        Row: Note;
        // id, created_at, updated_at are generated by DB
        Insert: Omit<Note, "id" | "created_at" | "updated_at">;
        // user_id is immutable
        Update: Partial<
          Omit<Note, "id" | "user_id" | "created_at" | "updated_at">
        >;
      };
    };
  };
};
